name: 'de_agent_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'de_agent_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  snowflake_warehouse: SNOWFLAKE_LEARNING_WH

models:
  de_agent_lakehouse:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +schema: int
