#!/usr/bin/env bash
# Adds maker file paths to .git/info/exclude so they are invisible to git
# without modifying any tracked file in the project.
#
# Safe to run multiple times — checks for existing entries before writing.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "Error: not inside a git repository." >&2
  exit 1
}

EXCLUDE_FILE="$REPO_ROOT/.git/info/exclude"
MARKER="# maker-lite-begin"

if grep -qF "$MARKER" "$EXCLUDE_FILE" 2>/dev/null; then
  echo "Maker-lite exclusions are already present in $EXCLUDE_FILE — nothing to do."
  exit 0
fi

# Warn if tasks/ already exists as a tracked directory in the repo
if git -C "$REPO_ROOT" ls-files --error-unmatch tasks/ &>/dev/null 2>&1; then
  echo ""
  echo "Warning: the project already tracks a 'tasks/' directory."
  echo "Using 'tasks/' for maker task tracking will conflict."
  echo "Rename the maker tasks directory and update CLAUDE.md before proceeding."
  echo "See the 'Naming Conflicts' section of MAKER_LITE.md."
  echo ""
  read -r -p "Continue anyway? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || exit 1
fi

cat >> "$EXCLUDE_FILE" << 'EOF'

# maker-lite-begin — local-only maker files; not committed to remote
# Generated by .project/scripts/setup-maker-lite.sh
# Remove the maker-lite-begin / maker-lite-end block to disable.
CLAUDE.md
MAKER_ONBOARDING.md
MAKER_ONBOARDING_PLAN.md
MAKER_LITE.md
.project/
tasks/
# maker-lite-end
EOF

echo ""
echo "Maker-lite exclusions added to $EXCLUDE_FILE"
echo ""
echo "Excluded paths (local only, invisible to git):"
echo "  CLAUDE.md"
echo "  MAKER_ONBOARDING.md"
echo "  MAKER_ONBOARDING_PLAN.md"
echo "  MAKER_LITE.md"
echo "  .project/"
echo "  tasks/"
echo ""
echo "Verify with: git status"
echo "Note: these exclusions are lost on a fresh clone. Re-run this script after cloning."
